### ISSUE TITLE
Traceback during pip install

### ISSUE THREAD

**Issue by bhundven** [vmware/vsphere-automation-sdk-python#108]
- [X] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [X] This API is compatible with my vCenter version 6.7update1
- [X] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk package version: 
$ pip list | grep v
pyvmomi                       6.7.1

- python version:
```python --version
Python 2.7.15+```

- vSphere version: N/A (but it is 6.7update1)

- Operating System/Shell (used to run SDK-based apps):
Debian 9
pipenv:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
ansible = "*"
pyvmomi = "*"
google-auth = "*"
apache-libcloud = "*"
ansible-lint = "*"
pycrypto = "*"
markupsafe = "*"

[requires]
python_version = "2.7"
```

## Steps or code snippet to reproduce
```
pipenv install
pipenv shell
git clone https://github.com/vmware/vsphere-automation-sdk-python.git
cd vsphere-automation-sdk-python
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:////home/bhundven/Projects/work/vsphere-automation-sdk-python/lib
```
## Actual behavior
```
$ pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:////home/bhundven/Projects/work/vsphere-automation-sdk-python/lib
Ignoring suds-jurko: markers 'python_version >= "3.0"' don't match your environment
Looking in indexes: https://pypi.org/simple, file://home/bhundven/Projects/work/vsphere-automation-sdk-python/lib
Collecting pyVmomi>=6.7 (from -r requirements.txt (line 1))
  Url 'file:////home/bhundven/Projects/work/vsphere-automation-sdk-python/lib/pyvmomi/' is ignored: it is neither a file nor a directory.
  Using cached https://files.pythonhosted.org/packages/ee/9a/7b24db4501e720fbd0a3578a8dde4b03d20b6fc3427e992dce19a3cf5cfc/pyvmomi-6.7.1.zip
Collecting suds (from -r requirements.txt (line 2))
  Url 'file:////home/bhundven/Projects/work/vsphere-automation-sdk-python/lib/suds/' is ignored: it is neither a file nor a directory.
  Using cached https://files.pythonhosted.org/packages/bc/d6/960acce47ee6f096345fe5a7d9be7708135fd1d0713571836f073efc7393/suds-0.4.tar.gz
Collecting tabulate (from -r requirements.txt (line 4))
  Url 'file:////home/bhundven/Projects/work/vsphere-automation-sdk-python/lib/tabulate/' is ignored: it is neither a file nor a directory.
  Using cached https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz
Collecting vapi-client-bindings==1.5.0 (from -r requirements.txt (line 5))
Exception:
Traceback (most recent call last):
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/index.py", line 572, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/index.py", line 530, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/index.py", line 675, in _get_pages
    page = self._get_page(location)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/index.py", line 793, in _get_page
    return _get_html_page(link, session=self.session)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/index.py", line 144, in _get_html_page
    "Cache-Control": "max-age=0",
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_internal/download.py", line 396, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 662, in send
    r.content
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 827, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/bhundven/.local/share/virtualenvs/ansible-it-ZGtxbozQ/local/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 760, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'exceptions.OSError' object has no attribute 'read'
```
## Expected behavior
The package installs

**Comment by tianhao64** [comment]
Looks like there is an extra "/" in the file path. Can you try:
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:///home/bhundven/Projects/work/vsphere-automation-sdk-python/lib
