### ISSUE TITLE
Unable to deploy a VM from Content Library - method expects PlacementSpec but got DeployPlacementSpec

### ISSUE THREAD

**Issue by samuelwagen** [vmware/vsphere-automation-sdk-python#110]
- [X] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [X] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [X] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk package version: 
pyvmomi                6.7.1
vapi-client-bindings   1.5.0
vapi-common-client     2.10.2
vapi-runtime           2.10.2
vapi-vmc-client        2.10.2
vmc-app-python-sdk     2.2.0.0.0.15184434
vmc-client-bindings    1.3.0

- python version: Python 3.7.0 and Python 2.7.15

- vSphere version: 6.7.0

- Operating System/Shell (used to run SDK-based apps): macOS/bash, Linux/bash

## Steps or code snippet to reproduce
```
vsphere-automation-sdk-python % PYTHONPATH=$(pwd):$PYTHONPATH python samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template.py --itemname linux-template --datacentername my-datacenter --datastorename vsan-datastore --vmname test-01 --foldername test-folder --resourcepoolname Resources -s vcenter.lab -u administrator@vsphere.local -p 'censored' -v
server: vcenter.lab
Library item ID: 6971994f-e8d3-493d-b5fe-8b8280a96972
Detected folder 'test-folder' as group-v92
Selecting ResourcePool 'resgroup-79'
Datastore MoId: datastore-88
Traceback (most recent call last):
  File "/tmp/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 79, in run
    attr()  # calling the method
  File "samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template.py", line 146, in _execute
    self.vm_id = self.client.vmtx_service.deploy(item_id, deploy_spec)
  File "/tmp/venv/lib/python3.7/site-packages/com/vmware/vcenter/vm_template_client.py", line 2101, in deploy
    'spec': spec,
  File "/tmp/venv/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/tmp/venv/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InvalidArgument: {messages : [LocalizableMessage(id='vapi.invoke.input.invalid', default_message='Unable to validate input to method com.vmware.vcenter.vm_template.library_items.deploy', args=['com.vmware.vcenter.vm_template.library_items.deploy']), LocalizableMessage(id='vapi.data.structure.field.invalid', default_message='Found invalid field spec in structure.', args=['spec']), LocalizableMessage(id='vapi.data.structure.field.invalid', default_message='Found invalid field placement in structure.', args=['placement']), LocalizableMessage(id='vapi.data.optional.validate', default_message='The given OptionalValue does not match the OptionalDefinition', args=[]), LocalizableMessage(id='vapi.data.structure.name.mismatch', default_message="Name mismatch for structure.  Expected 'com.vmware.vcenter.vm_template.library_items.placement_spec', but got 'com.vmware.vcenter.vm_template.library_items.deploy_placement_spec'", args=['com.vmware.vcenter.vm_template.library_items.placement_spec', 'com.vmware.vcenter.vm_template.library_items.deploy_placement_spec'])], data : None}
Traceback (most recent call last):
  File "/tmp/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 79, in run
    attr()  # calling the method
  File "samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template.py", line 146, in _execute
    self.vm_id = self.client.vmtx_service.deploy(item_id, deploy_spec)
  File "/tmp/venv/lib/python3.7/site-packages/com/vmware/vcenter/vm_template_client.py", line 2101, in deploy
    'spec': spec,
  File "/tmp/venv/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/tmp/venv/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InvalidArgument: {messages : [LocalizableMessage(id='vapi.invoke.input.invalid', default_message='Unable to validate input to method com.vmware.vcenter.vm_template.library_items.deploy', args=['com.vmware.vcenter.vm_template.library_items.deploy']), LocalizableMessage(id='vapi.data.structure.field.invalid', default_message='Found invalid field spec in structure.', args=['spec']), LocalizableMessage(id='vapi.data.structure.field.invalid', default_message='Found invalid field placement in structure.', args=['placement']), LocalizableMessage(id='vapi.data.optional.validate', default_message='The given OptionalValue does not match the OptionalDefinition', args=[]), LocalizableMessage(id='vapi.data.structure.name.mismatch', default_message="Name mismatch for structure.  Expected 'com.vmware.vcenter.vm_template.library_items.placement_spec', but got 'com.vmware.vcenter.vm_template.library_items.deploy_placement_spec'", args=['com.vmware.vcenter.vm_template.library_items.placement_spec', 'com.vmware.vcenter.vm_template.library_items.deploy_placement_spec'])], data : None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template.py", line 171, in <module>
    main()
  File "samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template.py", line 167, in main
    sample.main()
  File "/tmp/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 97, in main
    self.run()
  File "/tmp/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 85, in run
    raise Exception(e)
Exception: {messages : [LocalizableMessage(id='vapi.invoke.input.invalid', default_message='Unable to validate input to method com.vmware.vcenter.vm_template.library_items.deploy', args=['com.vmware.vcenter.vm_template.library_items.deploy']), LocalizableMessage(id='vapi.data.structure.field.invalid', default_message='Found invalid field spec in structure.', args=['spec']), LocalizableMessage(id='vapi.data.structure.field.invalid', default_message='Found invalid field placement in structure.', args=['placement']), LocalizableMessage(id='vapi.data.optional.validate', default_message='The given OptionalValue does not match the OptionalDefinition', args=[]), LocalizableMessage(id='vapi.data.structure.name.mismatch', default_message="Name mismatch for structure.  Expected 'com.vmware.vcenter.vm_template.library_items.placement_spec', but got 'com.vmware.vcenter.vm_template.library_items.deploy_placement_spec'", args=['com.vmware.vcenter.vm_template.library_items.placement_spec', 'com.vmware.vcenter.vm_template.library_items.deploy_placement_spec'])], data : None}
disconnecting the session
```

## Actual behavior
Error above
## Expected behavior
VM deployed from template

**Comment by tianhao64** [comment]
@samuelwagen, 6.7.0 doesn't have this specific API yet. Version 6.6.2 stated on top of the sample is a cloud release(VMware Cloud on AWS). 6.7.0 is the onprem release right after that, however, the APIs scope are finalized long before 6.6.2 was released. Therefore, a couple of APIs introduced as part of 6.6.2 cloud release are not available in 6.7.0 vCenter. 
The versioning pattern is a little big confusing as we have mixed onprem and cloud release schedules. We will try to address this issue to avoid such confusion in the future.
