### ISSUE TITLE
Error while running add_remove_hosts.py

### ISSUE THREAD

**Issue by vThinkBeyondVM** [vmware/vsphere-automation-sdk-python#130]
When I run this sample (C:\Professional\python\vsphere-automation-sdk-python\samples\vmc\sddc\add_remove_hosts.py) I hit below error: I am running from my python env set on windows 10

# Example: Add 1 ESX hosts to SDDC xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 259, in _visit_vapi_struct
    self.visit(typ.get_field(field))
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\lib\visitor.py", line 43, in visit
    return method(value)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 403, in visit_optional
    self.visit(typ.element_type)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\lib\visitor.py", line 43, in visit
    return method(value)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 113, in visit_string
    self.visit_primitive(typ)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 71, in visit_primitive
    self._out_value = typ.definition.new_value(self._in_value)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\data\definition.py", line 217, in new_value
    return data_value_factory(self.type, value)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\data\value.py", line 704, in data_value_factory
    return constructor(*args)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\data\value.py", line 188, in __init__
    raise CoreException(msg)
vmware.vapi.exception.CoreException: Invalid Type, expected String, instead got int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Professional\python\vsphere-automation-sdk-python\samples\vmc\sddc\add_remove_hosts.py", line 138, in <module>
    main()
  File "C:\Professional\python\vsphere-automation-sdk-python\samples\vmc\sddc\add_remove_hosts.py", line 133, in main
    esx_operations.add_host()
  File "C:\Professional\python\vsphere-automation-sdk-python\samples\vmc\sddc\add_remove_hosts.py", line 97, in add_host
    esx_config=esx_config)
  File "C:\Program Files\Python37\lib\site-packages\com\vmware\vmc\orgs\sddcs_client.py", line 220, in create
    'action': action,
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\stub.py", line 207, in native_invoke
    self._rest_converter_mode)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 1104, in convert_to_vapi
    binding_type.accept(visitor)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\type.py", line 40, in accept
    visitor.visit(self)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\lib\visitor.py", line 43, in visit
    return method(value)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 326, in visit_struct
    self._visit_python_dict(typ)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 305, in _visit_python_dict
    self.visit(field_type)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\lib\visitor.py", line 43, in visit
    return method(value)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 433, in visit_reference
    self.visit(typ.resolved_type)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\lib\visitor.py", line 43, in visit
    return method(value)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 318, in visit_struct
    self._visit_vapi_struct(typ)
  File "C:\Program Files\Python37\lib\site-packages\vmware\vapi\bindings\converter.py", line 265, in _visit_vapi_struct
    raise CoreException(msg, e)
vmware.vapi.exception.CoreException: Invalid field availability_zone in structure com.vmware.vmc.model.esx_config,
        Caused by: vmware.vapi.exception.CoreException: Invalid Type, expected String, instead got int

**Comment by vThinkBeyondVM** [comment]
I also get this error though "samples" package folder is available in directory. 

C:\Professional\python\vsphere-automation-sdk-python\samples>python.exe C:\Professional\python\vsphere-automation-sdk-python\samples\vmc\sddc\add_remove_hosts.py -r "xxxxxxxxxxxx" -o "xxxxxxxxxxxxxxxxxxxxxxxxxxxx" -s "xxxxxxxxxxxxxxxxxxxxxxx"
Traceback (most recent call last):
  File "C:\Professional\python\vsphere-automation-sdk-python\samples\vmc\sddc\add_remove_hosts.py", line 26, in <module>
    from samples.vmc.helpers.vmc_task_helper import wait_for_task
ModuleNotFoundError: No module named 'samples'

C:\Professional\python\vsphere-automation-sdk-python\samples>

Then I commented 
"from samples.vmc.helpers.vmc_task_helper import wait_for_task" and related code, after that I got an error that is reported in my 1st update.

**Comment by tianhao64** [comment]
@vThinkBeyondVM to use the helper method (wait_for_task) you need to add samples to your pythonpath: https://github.com/vmware/vsphere-automation-sdk-python#first-set-pythonpath-to-use-sdk-helper-methods

**Comment by tianhao64** [comment]
A couple of new fields were added to the esxconfig. The sample needs to be updated and pass a named argument (num_host) instead. Just updated the sample. Please try again.
