### ISSUE TITLE
create_vsphere_client error!

### ISSUE THREAD

**Issue by chaojidaxingxin** [vmware/vsphere-automation-sdk-python#149]
>>> import requests
>>> import urllib3
>>> from vmware.vapi.vsphere.client import create_vsphere_client
>>> session = requests.session()
>>> session.verify = False
>>> vsphere_client = create_vsphere_client(server='xx.xx.xx.xxx', username='root', password='root', session=session)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\vsphere\client.py", line 170, in create_vsphere_client
    hok_token=hok_token, private_key=private_key)
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\vsphere\client.py", line 111, in __init__
    session_id = session_svc.create()
  File "C:\Users\minchaol\anaconda\lib\site-packages\com\vmware\cis_client.py", line 197, in create
    return self._invoke('create', None)
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\bindings\stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\bindings\stub.py", line 243, in native_invoke
    method_result = self.invoke(ctx, method_id, data_val)
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\bindings\stub.py", line 179, in invoke
    ctx)
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\security\client\security_context_filter.py", line 99, in invoke
    self, service_id, operation_id, input_value, new_ctx)
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\provider\filter.py", line 76, in invoke
    service_id, operation_id, input_value, ctx)
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\protocol\client\msg\json_connector.py", line 79, in invoke
    response = self._do_request(VAPI_INVOKE, params)
  File "C:\Users\minchaol\anaconda\lib\site-packages\vmware\vapi\protocol\client\msg\json_connector.py", line 125, in _do_request
    http_response.data.raise_for_status()
  File "C:\Users\minchaol\anaconda\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://xx.xx.xx.xxx:443/api

**Comment by tianhao64** [comment]
@chaojidaxingxin is this an ESX host, or vCenter?

**Comment by tianhao64** [comment]
create_vsphere_client expects a vCenter IP or hostname.

**Comment by chaojidaxingxin** [comment]
Yes! I ignore of that. Thanks!
