### ISSUE TITLE
Could you please give me an example of VmtxLibraryItem.HardwareCustomizationSpec?

### ISSUE THREAD

**Issue by CoderFei** [vmware/vsphere-automation-sdk-python#152]
samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template.py
I use this sample to create vm and it can succeed.
I want to pass 'HardwareCustomizationSpec' to create a VM with a nic.
My code is like this
```
       # Build the deployment specification
        placement_spec = VmtxLibraryItem.DeployPlacementSpec(
            folder=folder_id,
            resource_pool=resource_pool_id)
        vm_home_storage_spec = VmtxLibraryItem.DeploySpecVmHomeStorage(
            datastore=datastore_id)
        disk_storage_spec = VmtxLibraryItem.DeploySpecDiskStorage(
            datastore=datastore_id)
        nics = {'network-27': {'network': 'network-27'}}
        cpu_update = VmtxLibraryItem.CpuUpdateSpec(
            num_cpus=4, num_cores_per_socket=1)
        memory_update = VmtxLibraryItem.MemoryUpdateSpec(memory=4)
        hardware_spec = VmtxLibraryItem.HardwareCustomizationSpec(
            nics=nics, cpu_update=cpu_update, memory_update=memory_update)
        deploy_spec = VmtxLibraryItem.DeploySpec(
            name=self.vm_name,
            placement=placement_spec,
            vm_home_storage=vm_home_storage_spec,
            disk_storage=disk_storage_spec,
            hardware_customization=hardware_spec,
            powered_on=True)
```

The result

> server: 192.168.84.33
Library item ID: f5e65730-a070-47e4-80d4-114a6752afe3
Detected folder 'Test' as group-v189
Selecting ResourcePool 'resgroup-190'
Datastore MoId: datastore-23
Traceback (most recent call last):
  File "samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template_hardware_cust.py", line 183, in <module>
    main()
  File "samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template_hardware_cust.py", line 179, in main
    sample.main()
  File "/root/dev/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 90, in main
    self.run()
  File "/root/dev/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 78, in run
    attr()  # calling the method
  File "samples/vsphere/contentlibrary/vmtemplate/deploy_vm_template_hardware_cust.py", line 158, in _execute
    self.vm_id = self.client.vmtx_service.deploy(item_id, deploy_spec)
  File "/root/venv/vsphere-automation/lib/python2.7/site-packages/com/vmware/vcenter/vm_template_client.py", line 2101, in deploy
    'spec': spec,
  File "/root/venv/vsphere-automation/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/root/venv/vsphere-automation/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InvalidArgument: {data : None, messages : [LocalizableMessage(default_message='The IDs for the field nics must be integers. The following provided IDs are invalid: [network-27].', args=['nics', '[network-27]'], id='com.vmware.vdcs.vmtx-main.invalid_device_ids_not_integer')]}
disconnecting the session

> vSphere Automation SDK for Python
nics ((dict of str and LibraryItems.EthernetUpdateSpec) or None) – Map of Ethernet network adapters to update. This attribute was added in vSphere API 6.7 U1. When clients pass a value of this class as a parameter, the key in the attribute dict must be an identifier for the resource type: com.vmware.vcenter.vm.hardware.Ethernet. When methods return a value of this class as a return value, the key in the attribute dict will be an identifier for the resource type: com.vmware.vcenter.vm.hardware.Ethernet. If None, all Ethernet adapters will remain connected to the same network as they were in the source virtual machine template. An Ethernet adapter with a MacAddressType of MANUAL will not change. An Ethernet adapter with a MacAddressType of GENERATED or ASSIGNED will receive a new address.

After I read the doc of vSphere Automation SDK for Python, I can not understand how to pass the parameter 'nics'.

Could you please give me an example of VmtxLibraryItem.HardwareCustomizationSpec?

Thanks!

**Comment by CoderFei** [comment]
# Build the deployment specification
        placement_spec = VmtxLibraryItem.DeployPlacementSpec(
            folder=folder_id,
            resource_pool=resource_pool_id)
        vm_home_storage_spec = VmtxLibraryItem.DeploySpecVmHomeStorage(
            datastore=datastore_id)
        disk_storage_spec = VmtxLibraryItem.DeploySpecDiskStorage(
            datastore=datastore_id)
        nics = {'network-27': {'network': 'network-27'}}
        cpu_update = VmtxLibraryItem.CpuUpdateSpec(
            num_cpus=4, num_cores_per_socket=1)
        memory_update = VmtxLibraryItem.MemoryUpdateSpec(memory=4)
        hardware_spec = VmtxLibraryItem.HardwareCustomizationSpec(
            nics=nics, cpu_update=cpu_update, memory_update=memory_update)
        deploy_spec = VmtxLibraryItem.DeploySpec(
            name=self.vm_name,
            placement=placement_spec,
            vm_home_storage=vm_home_storage_spec,
            disk_storage=disk_storage_spec,
            hardware_customization=hardware_spec,
            powered_on=True)

**Comment by CoderFei** [comment]
Maybe I missed the point in SDK doc. 
Does HardwareCustomizationSpec only support to update the existing Ethernet adapters in the source virtual machine template when deploying a new virtual machine?
New ethernet adapter can only be added to an existing virtual machine.
Is my understanding right?
@tianhao64
