### ISSUE TITLE
Problem in account_link_client.py

### ISSUE THREAD

**Issue by norikuro** [vmware/vsphere-automation-sdk-python#173]
When I tried sddc_crud.py to create sddc with python2.7 or python3, I got following error.
This seems something wrong in account_link_client.py.

 Example: Create a SDDC (sddc-single-nk) in org xxxxx-org-id-xxxx:
Traceback (most recent call last):
  File "samples/vmc/sddc/sddc_crud.py", line 227, in <module>
    main()
  File "samples/vmc/sddc/sddc_crud.py", line 219, in main
    sddc_operations.create_sddc()
  File "samples/vmc/sddc/sddc_crud.py", line 119, in create_sddc
    self.org_id)
  File "/usr/lib/python2.7/site-packages/com/vmware/vmc/orgs/account_link_client.py", line 280, in get
    'provider': provider,
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/stub.py", line 281, in native_invoke
    self._rest_converter_mode)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/converter.py", line 1092, in convert_to_python
    binding_type.accept(visitor)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/type.py", line 40, in accept
    visitor.visit(self)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/converter.py", line 618, in visit_list
    for elt_value in in_value]
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/converter.py", line 605, in _visit_list_element
    self.visit(typ)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/converter.py", line 854, in visit_reference
    self.visit(typ.resolved_type)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/converter.py", line 740, in visit_struct
    in_value.get_field(field_name), field_type)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/converter.py", line 696, in _visit_struct_field
    self.visit(typ)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/converter.py", line 1057, in visit_date_time
    self._in_value.value)
  File "/usr/lib/python2.7/site-packages/vmware/vapi/bindings/datetime_helper.py", line 169, in convert_from_rfc3339_to_datetime
    match = DateTimeConverter._rfc3339_dt_expr.match(datetime_str)
TypeError: expected string or buffer

**Comment by norikuro** [comment]
I tried orgs.account_link.ConnectedAccounts in my python scripts, I got same error.
vmc_client.orgs.account_link.ConnectedAccounts.get("xxx-org-id-xxxxx")

**Comment by kunal-pmj** [comment]
Hi @norikuro 

We are working on this issue.

thanks
Kunal

**Comment by tianhao64** [comment]
This issue is now fixed.
