### ISSUE TITLE
dns servers update on vCenter failed

### ISSUE THREAD

**Issue by alecorps** [vmware/vsphere-automation-sdk-python#197]
Hello guys,

When we try to update dns servers on a vcsa 6.7 appliance, we got an issue.
Following the code we used :

```
import requests
import urllib3

from vmware.vapi.vsphere.client import create_vsphere_client
session = requests.session()
session.verify = False
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
vsphere_client = create_vsphere_client(server='xxxxxxxxx', username='administrator@vsphere.local', password='xxxxxxx', session=session)
import com.vmware.appliance.networking.dns_client as dns_client
dns_config = dns_client.Servers.DNSServerConfig(servers=['x.x.x.x' , 'x.x.x.x'], mode=dns_client.Servers.DNSServerMode('static'))
spec = vsphere_client.appliance.Networking.ChangeSpec(hostname='xxxxx', dns=dns_config, sso_user="administrator@vsphere.local", sso_password="xxxxxx")
vsphere_client.appliance.Networking.change_task(spec)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cloud-user/.cache/pypoetry/virtualenvs/project-py3.6/lib64/python3.6/site-packages/com/vmware/appliance_client.py", line 1681, in change_task
    'spec': spec,
  File "/home/cloud-user/.cache/pypoetry/virtualenvs/project-py3.6/lib64/python3.6/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/home/cloud-user/.cache/pypoetry/virtualenvs/project-py3.6/lib64/python3.6/site-packages/vmware/vapi/bindings/stub.py", line 298, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.InternalServerError: {messages : [LocalizableMessage(id='vapi.data.invalid', default_message='Invalid Type, expected String, instead got TypeError', args=['String', 'TypeError'])], data : None, error_type : None}

```

Do you have the same issue or am I missing something?

**Comment by pgbidkar** [comment]
Hi @alecorps , Checking this, will try to reproduce and update you soon.
Thanks

**Comment by pgbidkar** [comment]
Hi @alecorps ,
Please can you try upgrading SDK packages? I am not seeing the error reported.

Please share what is the SDK version installed?

Thanks,
Pavan

**Comment by anusha94** [comment]
Closing due to inactivity on this bug. Feel free to reopen.
