### ISSUE TITLE
RecursionError when user does not specify certificates

### ISSUE THREAD

**Issue by Akasurde** [vmware/vsphere-automation-sdk-python#198]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [X] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

vapi-client-bindings               3.1.0
vapi-common-client                 2.12.0
vapi-runtime                       2.12.0
vmc-client-bindings                1.10.0
vmc-draas-client-bindings          1.0.0
vSphere-Automation-SDK             1.4.0

- python version:

Python 3.7.4

- vSphere version:
6.5

- Operating System/Shell (used to run SDK-based apps):
MacOS Mojave

## Steps or code snippet to reproduce
```
from vmware.vapi.vsphere.client import create_vsphere_client
import requests

session = requests.Session()
session.verify = True

client = create_vsphere_client(server=<HOSTNAME>, username=<USERNAME>, password=<PASSWORD>, session=session)
```
## Actual behavior
```
Traceback (most recent call last):
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/Volumes/data/venv3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/Volumes/data/venv3/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 368, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/data/venv3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Volumes/data/venv3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.65.200.241', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vsphe.py", line 7, in <module>
    client = create_vsphere_client(server="10.65.200.241", username="administrator@vsphere.local", password="Esxi@123$%", session=session)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/vsphere/client.py", line 170, in create_vsphere_client
    hok_token=hok_token, private_key=private_key)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/vsphere/client.py", line 111, in __init__
    session_id = session_svc.create()
  File "/Volumes/data/venv3/lib/python3.7/site-packages/com/vmware/cis_client.py", line 198, in create
    return self._invoke('create', None)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 266, in native_invoke
    method_result = self.invoke(ctx, method_id, data_val)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 202, in invoke
    ctx)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/security/client/security_context_filter.py", line 102, in invoke
    self, service_id, operation_id, input_value, ctx)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/provider/filter.py", line 76, in invoke
    service_id, operation_id, input_value, ctx)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py", line 79, in invoke
    response = self._do_request(VAPI_INVOKE, ctx, params)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py", line 122, in _do_request
    headers=request_headers, body=request_body))
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/protocol/client/rpc/requests_provider.py", line 98, in do_request
    cookies=http_request.cookies, timeout=timeout)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.65.200.241', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
Exception ignored in: <function VsphereClient.__del__ at 0x11063bdd0>
Traceback (most recent call last):
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/vsphere/client.py", line 136, in __del__
    if hasattr(self, 'session'):
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 443, in __getattr__
    return getattr(self._stub_factory, name)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 443, in __getattr__
    return getattr(self._stub_factory, name)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 443, in __getattr__
    return getattr(self._stub_factory, name)
  [Previous line repeated 496 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```
## Expected behavior
No recursion and more informative message about missing parameters.

**Comment by pgbidkar** [comment]
Hi @Akasurde , Thanks for reporting this.
I see different error
```
Traceback (most recent call last):
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 383, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.161.174.46', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/vsphere/client.py", line 172, in create_vsphere_client
    hok_token=hok_token, private_key=private_key)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/vsphere/client.py", line 113, in __init__
    session_id = session_svc.create()
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/com/vmware/cis_client.py", line 199, in create
    return self._invoke('create', None)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 266, in native_invoke
    method_result = self.invoke(ctx, method_id, data_val)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 202, in invoke
    ctx)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/security/client/security_context_filter.py", line 102, in invoke
    self, service_id, operation_id, input_value, ctx)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/provider/filter.py", line 76, in invoke
    service_id, operation_id, input_value, ctx)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py", line 79, in invoke
    response = self._do_request(VAPI_INVOKE, ctx, params)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/protocol/client/msg/json_connector.py", line 122, in _do_request
    headers=request_headers, body=request_body))
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/vmware/vapi/protocol/client/rpc/requests_provider.py", line 98, in do_request
    cookies=http_request.cookies, timeout=timeout)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/pbidkar/Documents/venvs/env-375/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.161.174.46', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```
Error Stack has the info **certificate verify failed**. Are you looking for more descriptive error from library than this big Error stack?
Thanks

**Comment by Akasurde** [comment]
Stack trace is OK. I am concerned about the last part, where it mentions the recursion error.

```
Exception ignored in: <function VsphereClient.__del__ at 0x11063bdd0>
Traceback (most recent call last):
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/vsphere/client.py", line 136, in __del__
    if hasattr(self, 'session'):
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 443, in __getattr__
    return getattr(self._stub_factory, name)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 443, in __getattr__
    return getattr(self._stub_factory, name)
  File "/Volumes/data/venv3/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 443, in __getattr__
    return getattr(self._stub_factory, name)
  [Previous line repeated 496 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by pgbidkar** [comment]
Hi @Akasurde , '**maximum recursion depth exceeded while calling a Python object'** This message is not present in the error stack I have pasted here https://github.com/vmware/vsphere-automation-sdk-python/issues/198#issuecomment-562129460

Please can you try upgrading your requests package?
Thanks

**Comment by rchadalawada** [comment]
@Akasurde, have you tried @pgbidkar's suggestion? Any update?

**Comment by Akasurde** [comment]
@rchadalawada Yes, I have tried @pgbidkar solution but still facing the same error. We are also facing the same issue in our CI environment https://github.com/ansible/ansible/issues/66475.

**Comment by anusha94** [comment]
Hi @Akasurde 

Thanks for pointing it out. The error was in a library file, I have fixed it, but it will be pushed out to github with the next release, some time in April.

With this fix, you will still get an error of `certificate verify failed` if there is no certificate present. I hope that is what you meant.

Thanks,
Anusha Hegde

**Comment by iamjhamukesh** [comment]
I am getting `com.vmware.vapi.std.errors_client.InternalServerError: {messages : [LocalizableMessage(id='vapi.bindings.method.impl.unexpected', default_message='Provider method implementation threw unexpected exception: null', args=['null'], params=None, localized=None)], data : None, error_type : None}` when I try to get `vsphere_client.vcenter.VM.list()`, can you tell why ?

**Comment by anusha94** [comment]
@iamjhamukesh 

Can you provide your code snippet and environment details?
Also your error is not relevant to the current thread, please feel free to open a new issue and we can discuss there.

**Comment by iamjhamukesh** [comment]
@anusha94 Ya sure, I have added in the new issue. If you are free, can you please look into that. Thanks !

**Comment by Akasurde** [comment]
For posterity - 

The solution is [here](https://github.com/ansible-collections/vmware/issues/49#issuecomment-598687489)
