### ISSUE TITLE
Error Cannot find service 'com.vmware.vcenter.VM'. when running quickstart example.

### ISSUE THREAD

**Issue by GreyArea765** [vmware/vsphere-automation-sdk-python#232]
Hi, trying to get up and running with this sdk.  I've run through the steps in the quickstart guide and set the export path.  I'm using the vSphere 7.0 release (14th April) against a 6.5 vSphere appliance.

My code is taken from the quickstart  example;

```
import requests
import urllib3
from vmware.vapi.vsphere.client import create_vsphere_client

session = requests.session()

# Disable cert verification for demo purpose. 
# This is not recommended in a production environment.
session.verify = False

# Disable the secure connection warning for demo purpose.
# This is not recommended in a production environment.
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Connect to a vCenter Server using username and password
vsphere_client = create_vsphere_client(
    server='myvcenter.local',
    username='user',
    password='password',
    session=session)

# List all VMs inside the vCenter Server
vsphere_client.vcenter.VM.list()
```

```
(vsphere-automation-sdk-python-hrolFB39) mattb@linstation:~/Documents/code/python/vsphere-automation-sdk-python$ export PYTHONPATH=${PWD}:$PYTHONPATH
vsphere-automation-sdk-python-hrolFB39) mattb@linstation:~/Documents/code/python/vsphere-automation-sdk-python$ echo $PYTHONPATH
/home/mattb/Documents/code/python/vsphere-automation-sdk-python:
(vsphere-automation-sdk-python-hrolFB39) mattb@linstation:~/Documents/code/python/vsphere-automation-sdk-python$ list.py
Traceback (most recent call last):
  File "list.py", line 23, in <module>
    vsphere_client.vcenter.VM.list()
  File "/home/mattb/.local/share/virtualenvs/vsphere-automation-sdk-python-hrolFB39/lib/python3.7/site-packages/com/vmware/vcenter_client.py", line 5153, in list
    'filter': filter,
  File "/home/mattb/.local/share/virtualenvs/vsphere-automation-sdk-python-hrolFB39/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 345, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/home/mattb/.local/share/virtualenvs/vsphere-automation-sdk-python-hrolFB39/lib/python3.7/site-packages/vmware/vapi/bindings/stub.py", line 298, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.OperationNotFound: {messages : [LocalizableMessage(id='vapi.method.input.invalid.interface', default_message="Cannot find service 'com.vmware.vcenter.VM'.", args=['com.vmware.vcenter.VM'], params=None, localized=None)], data : None, error_type : None}
```
Supporting info:

```
$ pip list | grep v
nsx-vmc-aws-integration-python-sdk 2.5.1.0.5.16221899
nsx-vmc-policy-python-sdk          2.5.1.0.5.16221899
pyvmomi                            7.0
vapi-client-bindings               3.3.0
vapi-common-client                 2.15.0
vapi-runtime                       2.15.0
vmc-client-bindings                1.26.0
vmc-draas-client-bindings          1.12.0
vSphere-Automation-SDK             1.34.0

$ python --version
Python 3.7.5
```

**Comment by anusha94** [comment]
@GreyArea765 

Could you please verify your VC version again? I was able to execute this snippet on a `6.5` version, but it errors out with `com.vmware.vapi.std.errors_client.OperationNotFound` on a `6.0` version

**Comment by GreyArea765** [comment]
Aaah you're right! - I'd forgotten that particular VC was still 6.0 - can confirm it works fine on a 6.5.

I can now see that VM.list() is not in the vmware package for 6.0
