### ISSUE TITLE
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/vapi-runtime/

### ISSUE THREAD

**Issue by patsevanton** [vmware/vsphere-automation-sdk-python#256]
- [*] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [*] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [*] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue) and [Troubleshooting wiki](https://github.com/vmware/vsphere-automation-sdk-python/wiki/Troubleshooting)

## Environment
- sdk package version: 

```
pyvcloud               23.0.0
pyvmomi                7.0.1
service-identity       16.0.0
vcd-api-schemas-type   9.1.2.dev10
```
- python version:

```
python --version
Python 2.7.17
Python 3.6.9
```
- vSphere version:
vSphere  inside VMware Cloud Director version: 10.2.0.17008054 Thu Oct 08 23:53:08 MSK 2020
- Operating System/Shell (used to run SDK-based apps):
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```
## Steps or code snippet to reproduce
```
 pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
Collecting git+https://github.com/vmware/vsphere-automation-sdk-python.git
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to /tmp/pip-nTFE0Q-build
Collecting lxml>=4.3.0 (from vSphere-Automation-SDK==1.44.0)
  Using cached https://files.pythonhosted.org/packages/15/55/ddcb9b3428c94aa2794f248897418178ee812288688f9cc8ec5147a4be47/lxml-4.6.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyVmomi>=6.7 (from vSphere-Automation-SDK==1.44.0)
Collecting vapi-runtime@ file://localhost//tmp/pip-nTFE0Q-build/lib/vapi-runtime/vapi_runtime-2.19.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.44.0)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/vapi-runtime/
```

**Comment by patsevanton** [comment]
```
 pip install --upgrade pip setuptools
```

Let`s fixed!!!
