### ISSUE TITLE
Cannot install anymore

### ISSUE THREAD

**Issue by ra-albrecht** [vmware/vsphere-automation-sdk-python#314]
### Describe the bug

When try to install/update I get an error message from pip on all machines I tried about a missing LICENSE.txt

```

pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
Collecting git+https://github.com/vmware/vsphere-automation-sdk-python.git
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to ./tmp/pip-_3ZQRQ-build
Collecting lxml>=4.3.0 (from vSphere-Automation-SDK==1.76.0)
  Downloading https://xxxx/packages/lxml/4.9.0/lxml-4.9.0-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (5.5MB)
    100% |████████████████████████████████| 5.6MB 270kB/s
Collecting nsx-policy-python-sdk@ file://localhost//home/xxxx/tmp/pip-_3ZQRQ-build/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-3.1.5.0.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.76.0)
  Downloading https://xxxx/packages/nsx-policy-python-sdk/0.0.1/nsx-policy-python-sdk-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxx/tmp/pip-build-Hyg1Gg/nsx-policy-python-sdk/setup.py", line 13, in <module>
        license=read('LICENSE.txt'),
      File "/home/xxx/tmp/pip-build-Hyg1Gg/nsx-policy-python-sdk/setup.py", line 5, in read
        with open(os.path.join(os.path.dirname(__file__), fname)) as fn:
    IOError: [Errno 2] No such file or directory: '/home/xxxx/tmp/pip-build-Hyg1Gg/nsx-policy-python-sdk/LICENSE.txt'
```

I report it here because these are packages from vmware without sources on github as far as I see.

### Reproduction steps

```bash
1.create python venv
2. try install vsphere python sdk 
3. error because no LICENSE.txt
```

### Expected behavior

Install dependencies packages from vmware without problems.

**Comment by shwetapurohit** [comment]
I am not able to reproduce this issue,
Which OS -? and python Version?

**Comment by ra-albrecht** [comment]
Ok. I have no idea what was wrong. I tested it with various pythons (3.6 - 3.10) on macos (homebrew/pyenv), linux and it didn't work. Some with nexus3 cache, some direct download from pypi... 

Today I do the same - it is working now. On every variant. With any combination. I have no clue whats going on. So sorry - may be the problem was somewhere but not on your side.

So thanks for your fast response - I close this myself.
