### ISSUE TITLE
pip install fails on missing LICENCE.txt

### ISSUE THREAD

**Issue by arthurzenika** [vmware/vsphere-automation-sdk-python#356]
### Describe the bug

```
pip install vsphere-automation-sdk
Collecting vsphere-automation-sdk
  Downloading vsphere-automation-sdk-0.0.1.tar.gz (988 bytes)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9gej4666/vsphere-automation-sdk_e19c6531b09d4c8697e83d336a713b14/setup.py", line 13, in <module>
          license=read('LICENSE.txt'),
        File "/tmp/pip-install-9gej4666/vsphere-automation-sdk_e19c6531b09d4c8697e83d336a713b14/setup.py", line 5, in read
          with open(os.path.join(os.path.dirname(__file__), fname)) as fn:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-9gej4666/vsphere-automation-sdk_e19c6531b09d4c8697e83d336a713b14/LICENSE.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Reproduction steps

1. `pip install vsphere-automation-sdk`
2.
3.
...

### Expected behavior

for `pip` to install latest published version of vsphere-automation-sdk which according to https://github.com/vmware/vsphere-automation-sdk-python/releases  is v8.0.0.1 not 0.0.1 as seen on https://pypi.org/project/vsphere-automation-sdk/#history

**Comment by aagrawal3** [comment]
Installation from PyPI is not supported at the moment. Please follow the installation guide from README.
https://github.com/vmware/vsphere-automation-sdk-python#quick-start-guide
