### ISSUE TITLE
vcenter.iso.iso_path.get_datastore_path() broken / missing

### ISSUE THREAD

**Issue by Yannik** [vmware/vsphere-automation-sdk-python#399]
### Describe the bug

Hi,
according to the docs, there should be a vcenter.iso.iso_path.get_datastore_path() method to get the datastore path of a content library item:
https://vdc-download.vmware.com/vmwb-repository/dcr-public/c2c7244e-817b-40d8-98f3-6c2ad5db56d6/af6d8ff7-1c38-4571-b72a-614ac319a62b/operations/com/vmware/vcenter/iso/iso_path.get_datastore_path-operation.html

However, when I try to use that method, I get an error that the `iso_path` attribute does not exist:

```
>>> client.vcenter.iso_path.get_datastore_path('52973462-d3fd-47c4-b532-c8b8a2dfc655')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yannik/.local/lib/python3.11/site-packages/vmware/vapi/bindings/stub.py", line 413, in __getattribute__
    result = object.__getattribute__(self, name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StubFactory' object has no attribute 'iso_path'
```

### Reproduction steps

```
client = create_vsphere_client(...)
client.vcenter.iso_path.get_datastore_path('<valid-library-item-guid>')
```

### Expected behavior

The datastore path of the library item should be returned.

**Comment by Yannik** [comment]
Looks like the method is not present in the newer docs: https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/iso/

Therefore I'd like changing this to a feature request. We really need this method.

**Comment by kunal-pmj** [comment]
The API is internal hence not present in the public SDK.
This is the latest API documentation : https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/iso/

This documentation has deprecated : https://vdc-download.vmware.com/vmwb-repository/dcr-public/c2c7244e-817b-40d8-98f3-6c2ad5db56d6/af6d8ff7-1c38-4571-b72a-614ac319a62b/operations/com/vmware/vcenter/iso/iso_path.get_datastore_path-operation.html

We will get back to you on the request to make this API available.

**Comment by Yannik** [comment]
Thank you @kunal-pmj. It is very important for us to be able to access this API call to get the datastore path of a ISO stored in the content library.
