### ISSUE TITLE
LICENSE.txt is missing

### ISSUE THREAD

**Issue by JakobHolstDK** [vmware/vsphere-automation-sdk-python#421]
### Describe the bug

 pip install vsphere-automation-sdk-python
Collecting vsphere-automation-sdk-python
  Using cached vsphere-automation-sdk-python-0.0.1.tar.gz (981 bytes)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/root/pyvim/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/pyvim/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/pyvim/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-eirgs6zl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-eirgs6zl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-eirgs6zl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-eirgs6zl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
        File "<string>", line 5, in read
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-exnz_899/vsphere-automation-sdk-python_98bd34e4c264408db8dffa5a7a7ee47f/LICENSE.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Reproduction steps

1.
2.
3.
...

### Expected behavior

The file is needed to pip install acording to setuptools standards

**Comment by bhagatp10** [comment]
The package on pypi is just the reserved namespace, there are no deliverables in it. If you want to install the sdk, you can follow [these steps](https://github.com/vmware/vsphere-automation-sdk-python?tab=readme-ov-file#installing-required-python-packages).
