### ISSUE TITLE
[embedded_psc_sso_workflow.py] socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by smrutim01** [vmware/vsphere-automation-sdk-python#44]
Hi

I am trying to run the Sample code of embedded_psc_sso_workflow.py but I am getting the following error.

```
#### Example: Login to vCenter server with embedded Platform Services Controller

Step 1: Connect to the Single Sign-On URL and retrieve the SAML bearer token.
Traceback (most recent call last):
  File "embedded_psc_sso_workflow.py", line 134, in <module>
    main()
  File "embedded_psc_sso_workflow.py", line 129, in main
    embedded_psc_sso_workflow.run()
  File "embedded_psc_sso_workflow.py", line 71, in run
    ssl_context=context)
  File "C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\common\sso.py", line 329, in get_bearer_saml_assertion
    ssl_context)
  File "C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\common\sso.py", line 255, in perform_request
    webservice.endheaders()
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\common\sso.py", line 167, in connect
    six.moves.http_client.HTTPSConnection.connect(self)
  File "C:\Python27\lib\httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "C:\Python27\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 11001] getaddrinfo failed

```
But if i use ,

```
context = ssl._create_unverified_context()
si = connect.SmartConnect(host=host,
                                          user=username,
                                          pwd=password,
                                          port=443, sslContext=context)
```

I am able to login and get the service instance. So there is no problem with address resolution.

**Comment by tianhao64** [comment]
@smrutim01 It seems it failed at getting bearer_token. Can you share the cmd you used to run the sample?

**Comment by smrutim01** [comment]
python embedded_psc_sso_workflow.py -s '10.172.109.40' -u 'Administrator@vsphere.local' -p 'xxxx' -c -v

**Comment by smrutim01** [comment]
Hi tianhao64 

Removing the Single quotes (') around the user and password worked. The Single quotes were taken as part of the string for Authentication and hence it was failing. Closing the issue.
