### ISSUE TITLE
external_psc_sso_workflow.py : faultcode: ns0:FailedAuthentication

### ISSUE THREAD

**Issue by smrutim01** [vmware/vsphere-automation-sdk-python#45]
While running the external_psc_sso_workflow I am getting Failed Authentication Error. But the credential that I am using is correct.

```
#### Example: Login to vCenter server with external Platform Services Controller

Step 1: Connect to the lookup service on the Platform Services Controller node: https://w3-stras-f5lb.eng.vmware.com/lookupservice/sdk

Step 2: Discover the Single Sign-On service URL from lookup service.
Sso URL: https://w3-stras-f5lb.eng.vmware.com/sts/STSService/vsphere.local

Step 3: Connect to the Single Sign-On URL and retrieve the SAML bearer token.
Traceback (most recent call last):
  File "external_psc_sso_workflow.py", line 218, in <module>
    main()
  File "external_psc_sso_workflow.py", line 213, in main
    external_psc_sso_workflow.run()
  File "external_psc_sso_workflow.py", line 151, in run
    ssl_context=context)
  File "C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\common\sso.py", line 329, in get_bearer_saml_assertion
    ssl_context)
  File "C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\common\sso.py", line 268, in perform_request
    raise SoapException(fault, *parsed_fault)
samples.vsphere.common.sso.SoapException: SoapException:
faultcode: ns0:FailedAuthentication
faultstring: Invalid credentials
faultxml: <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode xmlns:ns0="http://docs.oasis-open.org/ws-sx/ws-trust/200512">ns0:FailedAuthentication</faultcode><faultstring>Invalid credentials</faultstring></S:Fault></S:Body></S:Envelope>
```

**Comment by tianhao64** [comment]
@smrutim01 I was able to run the sample using below cmd. Can you double check if you are using the right username/password? Please try to use single quota instead of double. 

(py36) het-m03:vsphere-automation-sdk-python het$ python samples/vsphere/sso/external_psc_sso_workflow.py --lsurl https://10.192.33.249/lookupservice/sdk -u 'xxx' -p 'xxx' -v

lswsdl: /Users/het/github/vsphere-automation-sdk-python/samples/vsphere/sso/wsdl/lookupservice.wsdl
lsurl: https://10.192.33.249/lookupservice/sdk


#### Example: Login to vCenter server with external Platform Services Controller

Step 1: Connect to the lookup service on the Platform Services Controller node: https://10.192.33.249/lookupservice/sdk

Step 2: Discover the Single Sign-On service URL from lookup service.
Sso URL: https://sc2-rdops-vm01-dhcp-33-249.eng.vmware.com/sts/STSService/vsphere.local

Step 3: Connect to the Single Sign-On URL and retrieve the SAML bearer token.

Step 4. Discover the vAPI service URL from lookup service.
vAPI URL: https://sc2-rdops-vm01-dhcp-33-249.eng.vmware.com:443/api

Step 5. Login to vAPI service using the SAML bearer token.

Step 6: Creating and Deleting Tag Category...

Tag category created; Id: urn:vmomi:InventoryServiceCategory:8a1fc910-3889-47b0-a179-91c030b4e4c1:GLOBAL

VAPI session disconnected successfully...

**Comment by smrutim01** [comment]
python external_psc_sso_workflow.py --lsurl https://w3-stras-f5lb.eng.vmware.com/lookupservice/sdk  -u 'Administrator@vsphere.local' -p 'xxxxx' -v

```
lswsdl: C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\sso\wsdl\lookupservice.wsdl
lsurl: https://w3-stras-f5lb.eng.vmware.com/lookupservice/sdk


#### Example: Login to vCenter server with external Platform Services Controller

Step 1: Connect to the lookup service on the Platform Services Controller node: https://w3-stras-f5lb.eng.vmware.com/lookupservice/sdk
Traceback (most recent call last):
  File "external_psc_sso_workflow.py", line 218, in <module>
    main()
  File "external_psc_sso_workflow.py", line 213, in main
    external_psc_sso_workflow.run()
  File "external_psc_sso_workflow.py", line 128, in run
    self.mgmtinstancename, self.mgmtnodeid = lookupservicehelper.get_default_mgmt_node()
  File "C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\common\lookup_service_helper.py", line 323, in get_default_mgmt_node
    MultipleManagementNodeException.format(result))
samples.vsphere.common.lookup_service_helper.MultipleManagementNodeException: Multiple Management Node Found on server
Node name: w3-vc-ldu04.stls.local uuid: d7aeebcc-0a39-11e8-b9ae-005056bfe93c
Node name: h2-vc-ldu11.stls.local uuid: 454a7bda-09b8-11e8-8201-0050569311a2
Node name: w1-vc-ldu01.stls.local uuid: 05fbe0e2-09a7-11e8-8c66-005056bfaaf9
Node name: h2-vc-ldu12.stls.local uuid: e2407e54-09b7-11e8-be0b-005056931aed
Node name: w3-vc-ldu09.stls.local uuid: 87b1a35e-09b3-11e8-8125-005056bfaf38
Node name: h2-vc-ldu14.stls.local uuid: b24a3c6c-09b7-11e8-aeac-0050569364f5
Node name: h2-vc-ldu15.stls.local uuid: d8131856-09b7-11e8-9390-00505693436a
Node name: w3-vc-ldu07.stls.local uuid: de711162-09b2-11e8-9ed3-005056bf2b9d
Node name: w1-vc-ldu03.stls.local uuid: ce020ed2-09a6-11e8-b77b-005056bf4a05
Node name: w3-vc-ldu06.stls.local uuid: d7de3a8c-09b2-11e8-a140-005056bfcabc
Node name: w1-vc-ldu02.stls.local uuid: f0813712-09a6-11e8-8973-005056bffc24
Node name: w3-vc-ldu08.stls.local uuid: 04d8255c-09b3-11e8-8b90-005056bfd5ca
Node name: cloud02-w3.stls.local uuid: eceffb4a-0a66-11e8-b1fe-005056bf8b3d
Node name: h2-vc-ldu13.stls.local uuid: edd96122-09b7-11e8-87a9-005056935234
Node name: w1-vc-ldu04.stls.local uuid: c71c9bb4-09a6-11e8-a851-005056bf86ee


```
Then I commented the step 1 as it was returning all the management instance and the code was exiting.


python external_psc_sso_workflow.py --lsurl https://w3-stras-f5lb.eng.vmware.com/lookupservice/sdk  -u 'Administrator@vsphere.local' -p 'xxxx' -v

```
lswsdl: C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\sso\wsdl\lookupservice.wsdl
lsurl: https://w3-stras-f5lb.eng.vmware.com/lookupservice/sdk


#### Example: Login to vCenter server with external Platform Services Controller

Step 1: Connect to the lookup service on the Platform Services Controller node: https://w3-stras-f5lb.eng.vmware.com/lookupservice/sdk

Step 2: Discover the Single Sign-On service URL from lookup service.
Sso URL: https://w3-stras-f5lb.eng.vmware.com/sts/STSService/vsphere.local

Step 3: Connect to the Single Sign-On URL and retrieve the SAML bearer token.
Traceback (most recent call last):
  File "external_psc_sso_workflow.py", line 219, in <module>
    main()
  File "external_psc_sso_workflow.py", line 214, in main
    external_psc_sso_workflow.run()
  File "external_psc_sso_workflow.py", line 152, in run
    ssl_context=context)
  File "C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\common\sso.py", line 329, in get_bearer_saml_assertion
    ssl_context)
  File "C:\Users\smrutim\Documents\Projects\MyPrograms\Python\vsphere-automation-sdk-python\samples\vsphere\common\sso.py", line 268, in perform_request
    raise SoapException(fault, *parsed_fault)
samples.vsphere.common.sso.SoapException: SoapException:
faultcode: ns0:FailedAuthentication
faultstring: Invalid credentials
faultxml: <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode xmlns:ns0="http://docs.oasis-open.org/ws-sx/ws-trust/200512">ns0:FailedAuthentication</faultcode><faultstring>Invalid credentials</faultstring></S:Fault></S:Body></S:Envelope>
````

**Comment by smrutim01** [comment]
Hi tianhao64 

Removing the Single quotes (') around the user and password worked. The Single quotes were taken as part of the string for Authentication and hence it was failing. Closing the issue.
