### ISSUE TITLE
task_client.list(org_id) returns AttributeError: 'StructValue' object has no attribute 'value'

### ISSUE THREAD

**Issue by bryawood-aws** [vmware/vsphere-automation-sdk-python#52]
From the Python SDK for VMC:

```
>>> from com.vmware.vmc.model_client import Task
>>> from vmware.vapi.vmc.client import create_vmc_client
>>> import requests
>>> session = requests.Session()
>>> vmc_client = create_vmc_client("_expunged_",session)
>>> import atexit
>>> atexit.register(session.close)
<bound method Session.close of <requests.sessions.Session object at 0x7f844dd6c630>>
>>> task_client=vmc_client.orgs.Tasks
>>> org_id = '_expunged_from_this_issue_report_'
>>> task_client.list(org_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/com/vmware/vmc/orgs_client.py", line 493, in list
    'filter': filter,
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/stub.py", line 258, in native_invoke
    self._rest_converter_mode)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 1079, in convert_to_python
    binding_type.accept(visitor)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/type.py", line 40, in accept
    visitor.visit(self)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 617, in visit_list
    for elt_value in in_value]
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 617, in <listcomp>
    for elt_value in in_value]
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 604, in _visit_list_element
    self.visit(typ)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 841, in visit_reference
    self.visit(typ.resolved_type)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 727, in visit_struct
    in_value.get_field(field_name), field_type)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 683, in _visit_struct_field
    self.visit(typ)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 984, in visit_optional
    self.visit(typ.element_type)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 617, in visit_list
    for elt_value in in_value]
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 617, in <listcomp>
    for elt_value in in_value]
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 604, in _visit_list_element
    self.visit(typ)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 841, in visit_reference
    self.visit(typ.resolved_type)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 727, in visit_struct
    in_value.get_field(field_name), field_type)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 683, in _visit_struct_field
    self.visit(typ)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/lib/visitor.py", line 43, in visit
    return method(value)
  File "/usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py", line 527, in visit_string
    self._out_value = str(self._in_value.value)
AttributeError: 'StructValue' object has no attribute 'value'
>>>
```

This function was working without issue a couple of days ago on the same identical org_id, but now is persistently failing.

**Comment by bryawood-aws** [comment]
`>>> pdb.pm()
> /usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py(527)visit_string()
-> self._out_value = str(self._in_value.value)
(Pdb) p self._in_value
StructValue(name=None, values={'error_code_value': StringValue(value='skyscraper.nat.config.update.failed'), 'num_of_params': IntegerValue(value=1)})
  [..]
(Pdb) u
> /usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py(727)visit_struct()
-> in_value.get_field(field_name), field_type)
(Pdb) p field_name
'error_code'
(Pdb)
  [..]
(Pdb) u
> /usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py(617)<listcomp>()
-> for elt_value in in_value]
(Pdb) p in_value
*** NameError: name 'in_value' is not defined
(Pdb) p elt_value
StructValue(name=None, values={'error_code': StructValue(name=None, values={'error_code_value': StringValue(value='skyscraper.nat.config.update.failed'), 'num_of_params': IntegerValue(value=1)}), 'original_service': StringValue(value='Invalid IP Address input 192.168.1.3  for field rules.natRulesDtos[1].translatedAddress.'), 'original_service_error_code': StringValue(value=''), 'params': ListValue(values=[StringValue(value='vShield Edge'), StringValue(value='15012')]), 'default_message': StringValue(value='Nat config for edge vShield Edge failed.'), 'localized_message': StringValue(value='Nat config for edge vShield Edge failed.')})
(Pdb)`

Having a look at swagger, there are hundreds of finished tasks returned, several with the above error:

https://vmc.vmware.com/swagger/index.html#/task/get_orgs__org__tasks

`
 {
   "user_id": "...",
    "user_name": "...",
    "created": "2018-03-24T14:58:30.000498Z",
    "version": 2,
    "id": "...",
    "updated_by_user_id": "...",
    "updated_by_user_name": "...",
    "updated": "2018-03-24T14:58:30.000000Z",
    "status": "FAILED",
    "resource_id": "...",
    "resource_type": "sddc",
    "parent_task_id": null,
    "sub_status": "STARTED",
    "task_type": "NETWORK-ADD-NAT-RULE",
    "error_message": "com.vmware.skyscraper.common.SkyscraperException: Nat config for edge edge-2 failed.:skyscraper.nat.config.update.failed",
    "start_time": "2018-03-24T14:58:30.498000Z",
    "end_time": "2018-03-24T14:58:30.683000Z",
    "retries": 0,
    "task_version": "20161015",
    "progress_percent": 0,
    "estimated_remaining_minutes": -1,
    "task_progress_phases": null,
    "service_errors": [
      {
        "error_code": {
          "error_code_value": "skyscraper.nat.config.update.failed",
          "num_of_params": 1
        },
        "original_service": "Invalid IP Address input 192.168.1.3  for field rules.natRulesDtos[0].translatedAddress.",
        "original_service_error_code": "",
        "params": [
          "vShield Edge",
          "15012"
        ],
        "default_message": "Nat config for edge vShield Edge failed.",
        "localized_message": "Nat config for edge vShield Edge failed."
      }
    ],
    "params": {
      "GATEWAY_ID": "edge-2",
      "RULE": {
        "id": "",
        "name": "test NAT",
        "revision": 0,
        "action": "NATRULE_ACTION_DNAT",
        "public_ip": "...",
        "public_ports": "...",
        "internal_ip": "192.168.1.3 ",
        "internal_ports": "...",
        "protocol": "TCP",
        "rule_type": "user"
      }
    },
    "sla": "VMC_INTERNAL",
    "org_type": "INTERNAL_CORE",
    "phase_in_progress": "",
    "org_id": "..."
  },
`

Applying a filter, I am able to avoid the error:

>>> task_client.list(org='...',filter='created gt ''2018-03-25''')

Adding an additional exception handler in /usr/local/lib/python3.6/site-packages/vmware/vapi/bindings/converter.py line 530 resolved this issue for me:

`    def visit_string(self, typ):
        """
        Visit StringValue

        :type  typ: :class:`vmware.vapi.bindings.type.StringType`
        :param typ: Binding type of the value
        """
        try:
            self._out_value = str(self._in_value.value)
        except UnicodeError:
            self._out_value = self._in_value.value
        except AttributeError:
            self._out_value = None
`

**Comment by tianhao64** [comment]
@bryawood-aws This is a bug in console API. The response payload for error_code is inconsistent with the swagger schema which breaks the language binding deserializer. 

The actual payload for service_error is:
"service_errors": [
{
"error_code": {
"error_code_value": "skyscraper.vpn.ipsec.set.failed",
"num_of_params": 1
},
...
],

But based on the swagger schema, the field should be String
error_code* | string Localizable error code.

I have filed a bug against the team. Will update once the issue is fixed.

**Comment by tianhao64** [comment]
This issue is no longer reproducible in the latest binding(https://github.com/vmware/vsphere-automation-sdk-python/pull/124)
