### ISSUE TITLE
problem to install vsphere-automation-sdk-python exception occurs at vapi-client-bindings

### ISSUE THREAD

**Issue by metalbmw** [vmware/vsphere-automation-sdk-python#60]
- [v ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)

## Environment
- sdk package version: 
[root@python01 vsphere-automation-sdk-python]# pip list | grep v
pyudev              0.15
pyvmomi             6.7.0
virtualenv          15.2.0
pip                 10.0.0

- python version:
Python 2.7.5
- vSphere version:
6.0
## Steps or code snippet to reproduce
clone vsphere-automation-sdk-python was successful.
It cloned under root folder
[root@python01 vsphere-automation-sdk-python]# pwd
/root/vsphere-automation-sdk-python

[root@python01 vsphere-automation-sdk-python]# pip install -r requirements.txt --extra-index-url file:///`pwd`/lib

## Actual behavior
Ignoring suds-jurko: markers 'python_version >= "3.0"' don't match your environment
Looking in indexes: https://pypi.python.org/simple, file:////root/vsphere-automation-sdk-python/lib
Requirement already satisfied: pyVmomi>=6.5 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (6.7.0)
Collecting suds (from -r requirements.txt (line 2))
  Url 'file:////root/vsphere-automation-sdk-python/lib/suds/' is ignored: it is neither a file nor a directory.
  Using cached https://files.pythonhosted.org/packages/bc/d6/960acce47ee6f096345fe5a7d9be7708135fd1d0713571836f073efc7393/suds-0.4.tar.gz
Collecting tabulate (from -r requirements.txt (line 4))
  Url 'file:////root/vsphere-automation-sdk-python/lib/tabulate/' is ignored: it is neither a file nor a directory.
  Using cached https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz
Collecting vapi-client-bindings==1.2.0 (from -r requirements.txt (line 5))
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python2.7/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python2.7/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python2.7/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 243, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 307, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/site-packages/pip/_internal/index.py", line 484, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/site-packages/pip/_internal/index.py", line 442, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/site-packages/pip/_internal/index.py", line 587, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/site-packages/pip/_internal/index.py", line 705, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/site-packages/pip/_internal/index.py", line 814, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_internal/download.py", line 397, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 658, in send
    r.content
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 756, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'exceptions.OSError' object has no attribute 'read'

python code failed to read module. from vmware.vapi.vsphere.client import create_vsphere_client is not working

## Expected behavior
from vmware.vapi.vsphere.client import create_vsphere_client  should work and python code allow to connect vcenter server.

Can anyone tell me what I have done wrong?

Thank you

**Comment by tianhao64** [comment]
```Seems there is a typo in the README. file:///`pwd`/lib should be file://`pwd`/lib. But seems 3 /// should still work.```
Are you using a virtual env? It's highly recommended to use one so user installed modules won't conflict with the system ones. Please follow this if you haven't done so: https://github.com/vmware/vsphere-automation-sdk-python#prepare-a-python-development-environment. 
It's also recommended to use newer python version. Please try to upgrade python, install virtual env and install the modules again.

**Comment by wonhiwon** [comment]
thank you after update python with 2.7.14 it works

**Comment by meetdash** [comment]
same issue. tried everything. still not working.

python --version
Python 3.6.3

I'm working on Windows 10.

![vsphereautpsdkerror](https://user-images.githubusercontent.com/19898819/40954656-25f37968-68a3-11e8-9b59-1d40eae110b7.png)

**Comment by tianhao64** [comment]
@meetdash Windows file path cmd is different from linux/mac. Can you try:
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:\\%CD%\lib

**Comment by meetdash** [comment]
it worked. thanks!!

**Comment by lihualong0328** [comment]
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:\\F:\PycharmProjects\RemoteTarget\vsphere-automation-sdk-python-master\lib

it`s works!
