### ISSUE TITLE
vmconf = vim.vm.ConfigSpec(numCPUs=1, memoryMB=mem)

### ISSUE THREAD

**Issue by khalilnawar** [vmware/vsphere-automation-sdk-python#97]
Hi,
please how to correct this problem:
Traceback (most recent call last):
  File "C:/Users/khalil/PycharmProjects/vmware/finalScript/pyvmomicreateVM.py", line 34, in <module>
    vmconf = vim.vm.ConfigSpec(numCPUs=1, memoryMB=mem)
AttributeError: 'module' object has no attribute 'vm'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
WindowsError: [Error 32] Le processus ne peut pas acc�der au fichier car ce fichier est utilis� par un autre processus: 'c:\\users\\khalil\\appdata\\local\\temp\\tmp4xh6zd.py'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
WindowsError: [Error 32] Le processus ne peut pas acc�der au fichier car ce fichier est utilis� par un autre processus: 'c:\\users\\khalil\\appdata\\local\\temp\\tmp4xh6zd.py'

**Comment by tianhao64** [comment]
@khalilnawar Are you using pyvmomi? Can you post the complete script?

**Comment by tianhao64** [comment]
@khalilnawar I am closing this due to lack of info. Please post your script if you still see this issue.
