### ISSUE TITLE
ImportError: No module named samples.vsphere.common.sample_base

### ISSUE THREAD

**Issue by FumbleBe** [vmware/vsphere-automation-sdk-python#99]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-python/releases)
- [x] This API is compatible with my vCenter version (You can get the info from '__vcenter_version__' in each sample)
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-python/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- sdk package version: 
pyvmomi (6.7.0.2018.9)
service-identity (17.0.0)
vapi-client-bindings (1.3.1)
vapi-common-client (2.9.0)
vapi-runtime (2.9.0)
vapi-vmc-client (2.9.0)
virtualenv (16.0.0)
vmc-app-python-sdk (2.2.0.0.0.15184434)
vmc-client-bindings (1.2.0)

- python version:
Python 2.7.15rc1

- vSphere version:
6.0.0
- Operating System/Shell (used to run SDK-based apps):
Ubuntu 18.04.1
## Steps or code snippet to reproduce
python tagging_workflow.py --server 'IP' --username 'LOGIN' --password 'PASSWD' --clustername 'MAQ' --categoryname 'Cat' --categorydesc 'category' --tagname 'Tag' -tagdesc 'Tag' -v
## Actual behavior
Traceback (most recent call last):
  File "tagging_workflow.py", line 26, in <module>
    from samples.vsphere.common.sample_base import SampleBase
ImportError: No module named samples.vsphere.common.sample_base

## Expected behavior
Execution of the workflow

**Comment by FumbleBe** [comment]
Just figured out the issue. It was because of my PYTHONPATH environment variable... (Sorry I'm not familiar with Python) setting it to 

> export PYTHONPATH=. 

Solved the problem. But the workflow still doesn't work... Now, it says:

```
creating a new tag category...
Traceback (most recent call last):
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 79, in run
    attr()  # calling the method
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/tagging/tagging_workflow.py", line 131, in _execute
    CategoryModel.Cardinality.MULTIPLE)
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/tagging/tagging_workflow.py", line 179, in create_tag_category
    return self.category_svc.create(create_spec)
  File "/home/run/environments/vmware_sdk/lib/python3.5/site-packages/com/vmware/cis/tagging_client.py", line 392, in create
    'create_spec': create_spec,
  File "/home/run/environments/vmware_sdk/lib/python3.5/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/home/run/environments/vmware_sdk/lib/python3.5/site-packages/vmware/vapi/bindings/stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.UnexpectedInput: {messages : [LocalizableMessage(args=['[category_id]', 'com.vmware.cis.tagging.category.create_spec'], default_message="Champs [category_id] inattendus trouvÃ©s dans la structure 'com.vmware.cis.tagging.category.create_spec'.", id='vapi.data.structure.field.unexpected')], data : None}
Traceback (most recent call last):
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 79, in run
    attr()  # calling the method
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/tagging/tagging_workflow.py", line 131, in _execute
    CategoryModel.Cardinality.MULTIPLE)
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/tagging/tagging_workflow.py", line 179, in create_tag_category
    return self.category_svc.create(create_spec)
  File "/home/run/environments/vmware_sdk/lib/python3.5/site-packages/com/vmware/cis/tagging_client.py", line 392, in create
    'create_spec': create_spec,
  File "/home/run/environments/vmware_sdk/lib/python3.5/site-packages/vmware/vapi/bindings/stub.py", line 317, in _invoke
    return self._api_interface.native_invoke(ctx, _method_name, kwargs)
  File "/home/run/environments/vmware_sdk/lib/python3.5/site-packages/vmware/vapi/bindings/stub.py", line 275, in native_invoke
    self._rest_converter_mode)
com.vmware.vapi.std.errors_client.UnexpectedInput: {messages : [LocalizableMessage(args=['[category_id]', 'com.vmware.cis.tagging.category.create_spec'], default_message="Champs [category_id] inattendus trouvÃ©s dans la structure 'com.vmware.cis.tagging.category.create_spec'.", id='vapi.data.structure.field.unexpected')], data : None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/tagging/tagging_workflow.py", line 216, in <module>
    main()
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/tagging/tagging_workflow.py", line 211, in main
    tagging_workflow.main()
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 97, in main
    self.run()
  File "/home/run/vsphere-automation-sdk-python/samples/vsphere/common/sample_base.py", line 85, in run
    raise Exception(e)
Exception: {messages : [LocalizableMessage(args=['[category_id]', com.vmware.cis.tagging.category.create_spec'], default_message="Champs [category_id] inattendus trouvÃ©s dans la structure 'com.vmware.cis.tagging.category.create_spec'.", id='vapi.data.structure.field.unexpected')], data : None}
disconnecting the session

```

**Comment by tianhao64** [comment]
@FumbleBe 
Does your cluster name, catalog name or description contain non-ascii chars? 
Can you check your server log to see if you can get more stacktrace?

**Comment by FumbleBe** [comment]
Ok, so, managed to find out what was wrong...

Despite the fact that my vcenter was in 6.0.0, and it is suppose to work with this version, it seems that the build was probably too old (3339084).
I update it to build 9313458, and now, it is working...

**Comment by houcinedz** [comment]
can you explain to me how i can do that !!
